export const data = [
    { category: "cars", title: "BMW" },
    { category: "cars", title: "Volvo" },
    { category: "fruits", title: "Melon" },
    { category: "animals", title: "Cat" },
    { category: "cars", title: "Mustang" },
    { category: "animals", title: "Dog" },
    { category: "fruits", title: "Banana" },
    { category: "fruits", title: "Apple" },
    { category: "cars", title: "Audi" },
    { category: "animals", title: "Elephant" },
    { category: "fruits", title: "Orange" },
    { category: "cars", title: "Toyota" },
    { category: "animals", title: "Lion" },
    { category: "fruits", title: "Grapes" },
    { category: "fruits", title: "Pineapple" },
    { category: "cars", title: "Honda" },
    { category: "animals", title: "Giraffe" },
    { category: "fruits", title: "Strawberry" },
    { category: "cars", title: "Ford" },
    { category: "animals", title: "Panda" },
    { category: "fruits", title: "Cherry" },
  ];
  